config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # 保存の成功をここで扱う。
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
     <%= link_to "Tripstudio", '#', id: "logo" %>
      <nav>
       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Home",   '#' %></li>
         <li><%= link_to "Log in", '#' %></li>
       </ul>
      </nav>
     </div>
   </header>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tripstudio</title>
  </head>
  <body>
    <div class="center jumbotron">
     <h1>旅先の写真をシェアしよう！</h1>
     <h2>このサイトは旅行先の写真を投稿できるサイトです</h2>
       <%= link_to "登録はこちら", new_user_path, class: "btn btn-lg btn-primary" %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>user signup</title>
  </head>
  <body>
    <h1>ユーザー登録</h1>

    <div class="row">
     <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
       <%= f.label :name %>
       <%= f.text_field :name %>

       <%= f.label :email %>
       <%= f.email_field :email %>

       <%= f.label :password %>
       <%= f.password_field :password %>

       <%= f.label :password_confirmation, "Confirmation" %>
       <%= f.password_field :password_confirmation %>

       <%= f.submit "アカウント作成", class: "btn btn-primary" %>
      <% end %>
    </div>
   </div>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
   <div class="row">
    <aside class="col-md-4">
     <section class="user_info">
       <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
       </h1>
     </section>
    </aside>
   </div>
  </body>
</html>